-- Include your create table DDL statements in this file.
-- Make sure to terminate each statement with a semicolon (;)

-- LEAVE this statement on. It is required to connect to your database.
CONNECT TO COMP421;

-- Remember to put the create table ddls for the tables with foreign key references
--    ONLY AFTER the parent tables have already been created.

-- This is only an example of how you add create table ddls to this file.
--   You may remove it.


CREATE TABLE User
 (email VARCHAR(50) NOT NULL, 
 firstName VARCHAR(50),
 lastName VARCHAR(50),
 address VARCHAR(100),
 birthDate DATE,
 password VARCHAR(50),
 cardNumber INTEGER,
 expirationDate DATE,
 cardHolder VARCHAR(100),
 CVV INTEGER CHECK( CVV > 0 AND CVV < 10000),
 PRIMARY KEY (email));

 CREATE TABLE Admin
 (email VARCHAR(50) NOT NULL,
 PRIMARY KEY (email),
 FOREIGN KEY (email) REFERENCES User);

 CREATE TABLE Buyer
 (email VARCHAR(50) NOT NULL,
  PRIMARY KEY (email),
 FOREIGN KEY (email) REFERENCES User);

 CREATE TABLE Seller
 (email VARCHAR(50) NOT NULL,
  PRIMARY KEY (email),
 FOREIGN KEY (email) REFERENCES User);

 CREATE TABLE Post
 (postId BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
  creationDate DATE,
  status VARCHAR(30) CHECK (status IN ('open', 'closed', 'deleted', 'archived')),
  email VARCHAR(50),
  PRIMARY KEY (postId),
  FOREIGN KEY (email) REFERENCES Seller );
 
 CREATE TABLE Auction
 (postId BIGINT NOT NULL,
  highestBid INTEGER,
  deadline DATE,
  PRIMARY KEY (postId),
  FOREIGN KEY (postId) REFERENCES Post);

 CREATE TABLE Cart
 (email VARCHAR(50) NOT NULL,
  totalPrice DECIMAL(31, 2) NOT NULL WITH DEFAULT 0,
  PRIMARY KEY (email),
  FOREIGN KEY (email) REFERENCES Buyer);

 CREATE TABLE Card
 (postId BIGINT NOT NULL,
  cardName VARCHAR(50) NOT NULL,
  description VARCHAR(100),
  type VARCHAR(50) NOT NULL,
  cardCondition INTEGER NOT NULL CHECK (cardCondition > 0 AND cardCondition < 6),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  price DECIMAL(31, 2) NOT NULL CHECK (price > 0),
  PRIMARY KEY (postId, cardName, type, cardCondition),
  FOREIGN KEY (postId) REFERENCES Post);

 CREATE TABLE Wishlist
 (email VARCHAR(50) NOT NULL,
  PRIMARY KEY (email),
  FOREIGN KEY (email) REFERENCES User);

 CREATE TABLE Order
 (receipt VARCHAR(100) NOT NULL,
  email VARCHAR(50) NOT NULL,
  status VARCHAR(50) CHECK (status IN ('pending', 'completed', 'canceled')) DEFAULT 'pending',
  PRIMARY KEY (receipt),
  FOREIGN KEY (email) REFERENCES Buyer); 

 CREATE TABLE Review
 (reviewId BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL, 
 reviewScore INTEGER CHECK (reviewScore > 0 AND reviewScore < 6),
 description VARCHAR(50),
 reviewDate DATE,
 sellerEmail VARCHAR(50) NOT NULL,
 postId BIGINT NOT NULL,
 buyerEmail VARCHAR(50) NOT NULL,
 receipt VARCHAR(100) NOT NULL,
 PRIMARY KEY (reviewId, sellerEmail, postId),
 FOREIGN KEY (sellerEmail) REFERENCES Seller,
 FOREIGN KEY (postId) REFERENCES Post,
 FOREIGN KEY (buyerEmail) REFERENCES Buyer,
 FOREIGN KEY (receipt) REFERENCES Order);

 CREATE TABLE Bids
 (email VARCHAR(50) NOT NULL,
  postId BIGINT NOT NULL,
  bidAmount INTEGER,
  PRIMARY KEY (email, postId),
  FOREIGN KEY (email) REFERENCES Buyer,
  FOREIGN KEY (postId) REFERENCES Auction);

 CREATE TABLE Includes
 (email VARCHAR(50) NOT NULL,
  postId BIGINT  NOT NULL,
  cardName VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  cardCondition INTEGER NOT NULL CHECK (cardCondition > 0 AND cardCondition < 6),
  PRIMARY KEY (email, postId, cardName, type, cardCondition),
  FOREIGN KEY (email) REFERENCES User,
  FOREIGN KEY (postId, cardName, type, cardCondition) REFERENCES Card);
  
 CREATE TABLE Checks 
 (reviewId BIGINT NOT NULL,
  email VARCHAR(50) NOT NULL,
  sellerEmail VARCHAR(50) NOT NULL,
  postId BIGINT NOT NULL,
  PRIMARY KEY (reviewId, email, sellerEmail, postId),
  FOREIGN KEY (email) REFERENCES Admin,
  FOREIGN KEY (reviewId, sellerEmail, postId) REFERENCES Review);

  CREATE TABLE Belongs 
 (email VARCHAR(50) NOT NULL,
  postId BIGINT NOT NULL,
  PRIMARY KEY (email, postId),
  FOREIGN KEY (postId) REFERENCES Post,
  FOREIGN KEY (email) REFERENCES Buyer);

  CREATE TABLE Moderates 
 (postId BIGINT NOT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY (postId, email),
  FOREIGN KEY (postId) REFERENCES Post,
  FOREIGN KEY (email) REFERENCES Admin);

  CREATE TABLE Contains 
 (receipt VARCHAR(100) NOT NULL,
  postId BIGINT NOT NULL,
  PRIMARY KEY (receipt, postId),
  FOREIGN KEY (postId) REFERENCES Post,
  FOREIGN KEY (receipt) REFERENCES Order);
